# USERS CRUD
# GET ALL USERS WITH FOLLOWINGS AND SUBS
GET http://localhost:5173/api/users HTTP/1.1

###
# CREATE NEW USER
POST http://localhost:5173/api/users HTTP/1.1
content-type: application/json

{
    "email" : "regular@user.com",
    "password" : "Regularpass@02",
    "username" : "Regular user"
}

###
# SUPERUSER LOGIN
POST http://localhost:5173/api/userlogin HTTP/1.1
content-type: application/json

{
    "email" : "sanradsets@gmail.com",
    "password" : "msJ#JPcFpQn8d!W"
}
###
# REGULAR LOGIN
POST http://localhost:5173/api/userlogin HTTP/1.1
content-type: application/json

{
    "email" : "regular@user.com",
    "password" : "Regularpass@02"
}

###
# GET SINGLE USER
GET http://localhost:5173/api/users/3 HTTP/1.1

###
# EDIT USERS username
PATCH http://localhost:5173/api/users/2b55f1e3-10b8-4db7-971c-1bd00f8150d1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IjhteW5FcDczUzBNM2ZSMjgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2F3Z3J2anlzZHhieXZ1eHN6aGloLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyYjU1ZjFlMy0xMGI4LTRkYjctOTcxYy0xYmQwMGY4MTUwZDEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQwMzA0MzcyLCJpYXQiOjE3NDAzMDA3NzIsImVtYWlsIjoic2FucmFkc2V0c0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoic2FucmFkc2V0c0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiIyYjU1ZjFlMy0xMGI4LTRkYjctOTcxYy0xYmQwMGY4MTUwZDEifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc0MDMwMDc3Mn1dLCJzZXNzaW9uX2lkIjoiOTk2OWRhOTItY2YwZC00NTcyLWIxMWQtZmU2ZTc0YjkzY2IyIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.n2N-qNCb-UygETeQM1AdeJy_QHMHvnQAAFd_WoR7Zeg

{
    "username" : "sanedited"
}
###
# EDIT USERS AVATAR
PATCH http://localhost:5173/api/users/16/avatar HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJlZ3VsYXJAdXNlci5jb20iLCJpZCI6MTYsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMxMjY2ODkzLCJleHAiOjE3MzEyNzA0OTN9.EJUuoFbu6ImdZ6wHV6US3CP-fJl-IytMH41jh2oC55M

{
    "avatar_url" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFI7xKW1DpY1MyHw8GABbqeyGKB0ZmNmQVZQ&s"
}

###
# ADD SUBSCRIPTION RELATION 
POST http://localhost:5173/api/users/14/subscriptions HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlckB1c2VyLmNvbSIsImlkIjoxNCwicm9sZSI6InN1cGVydXNlciIsImlhdCI6MTczMTIzMDUwOCwiZXhwIjoxNzMxMjM0MTA4fQ.0ypWblkIVxxZEuK2Mu7k1YHPck4HLG9kIH8VRmRbU6o

{
    "podcasterId" : 40,
    "stipend" : 30
}
###
# ADD FOllWINGS RELATION 
POST http://localhost:5173/api/users/14/followings HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlckB1c2VyLmNvbSIsImlkIjoxNCwicm9sZSI6InN1cGVydXNlciIsImlhdCI6MTczMTIzMDUwOCwiZXhwIjoxNzMxMjM0MTA4fQ.0ypWblkIVxxZEuK2Mu7k1YHPck4HLG9kIH8VRmRbU6o

{
    "podcastId" : 23
}

# UPDATE INFO OF PODCASTER BY LOGGEDIN PODCASTER
###
PUT http://localhost:5173/api/users/16 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJlZ3VsYXJAdXNlci5jb20iLCJpZCI6MTYsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMxMjcxNjg0LCJleHAiOjE3MzEyNzUyODR9.Js07SotfWi6ixGsvs4flaKwiyvRh72vk1_WllG-0gms

{   
    "username" : "upddatedusername",
    "balance" : 300,
    "about": "thisi is an updated bio",
    "avatar_url": "thisisuorl.com"
}

###
# DELETE FollWINGS RELATION 
DELETE http://localhost:5173/api/users/14/followings HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlckB1c2VyLmNvbSIsImlkIjoxNCwicm9sZSI6InN1cGVydXNlciIsImlhdCI6MTczMTIzMDUwOCwiZXhwIjoxNzMxMjM0MTA4fQ.0ypWblkIVxxZEuK2Mu7k1YHPck4HLG9kIH8VRmRbU6o

{
    "podcastId" : 23
}

###
# DELETE FollWINGS RELATION 
DELETE http://localhost:5173/api/users/14 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlckB1c2VyLmNvbSIsImlkIjoxNCwicm9sZSI6InN1cGVydXNlciIsImlhdCI6MTczMTIzMDUwOCwiZXhwIjoxNzMxMjM0MTA4fQ.0ypWblkIVxxZEuK2Mu7k1YHPck4HLG9kIH8VRmRbU6o

