# USERS CRUD
# GET ALL USERS WITH FOLLOWINGS AND SUBS
GET http://localhost:5173/api/users HTTP/1.1

###
# CREATE NEW USER
POST http://localhost:5173/api/users HTTP/1.1
content-type: application/json

{
    "email" : "regular@user.com",
    "password" : "Regularpass@02",
    "username" : "Regular user"
}

###
# SUPERUSER LOGIN
POST http://localhost:5173/api/userlogin HTTP/1.1
content-type: application/json

{
    "email" : "super@user.com",
    "password" : "Superpass@02"
}
###
# REGULAR LOGIN
POST http://localhost:5173/api/userlogin HTTP/1.1
content-type: application/json

{
    "email" : "regular@user.com",
    "password" : "Regularpass@02"
}

###
# GET SINGLE USER
GET http://localhost:5173/api/users/3 HTTP/1.1

###
# EDIT USERS username
PATCH http://localhost:5173/api/users/8 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJlZ3VsYXJAdXNlci5jb20iLCJpZCI6OCwicm9sZSI6bnVsbCwiaWF0IjoxNzM5Njk4MTA0LCJleHAiOjE3Mzk3MDE3MDR9.H217NYGp64QvV2rQpY8hRNYFh51uM9ydIaBFYt1wwjA

{
    "username" : "another new username for regular user"
}
###
# EDIT USERS AVATAR
PATCH http://localhost:5173/api/users/16/avatar HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJlZ3VsYXJAdXNlci5jb20iLCJpZCI6MTYsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMxMjY2ODkzLCJleHAiOjE3MzEyNzA0OTN9.EJUuoFbu6ImdZ6wHV6US3CP-fJl-IytMH41jh2oC55M

{
    "avatar_url" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFI7xKW1DpY1MyHw8GABbqeyGKB0ZmNmQVZQ&s"
}

###
# ADD SUBSCRIPTION RELATION 
POST http://localhost:5173/api/users/14/subscriptions HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlckB1c2VyLmNvbSIsImlkIjoxNCwicm9sZSI6InN1cGVydXNlciIsImlhdCI6MTczMTIzMDUwOCwiZXhwIjoxNzMxMjM0MTA4fQ.0ypWblkIVxxZEuK2Mu7k1YHPck4HLG9kIH8VRmRbU6o

{
    "podcasterId" : 40,
    "stipend" : 30
}
###
# ADD FOllWINGS RELATION 
POST http://localhost:5173/api/users/14/followings HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlckB1c2VyLmNvbSIsImlkIjoxNCwicm9sZSI6InN1cGVydXNlciIsImlhdCI6MTczMTIzMDUwOCwiZXhwIjoxNzMxMjM0MTA4fQ.0ypWblkIVxxZEuK2Mu7k1YHPck4HLG9kIH8VRmRbU6o

{
    "podcastId" : 23
}

# UPDATE INFO OF PODCASTER BY LOGGEDIN PODCASTER
###
PUT http://localhost:5173/api/users/16 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJlZ3VsYXJAdXNlci5jb20iLCJpZCI6MTYsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMxMjcxNjg0LCJleHAiOjE3MzEyNzUyODR9.Js07SotfWi6ixGsvs4flaKwiyvRh72vk1_WllG-0gms

{   
    "username" : "upddatedusername",
    "balance" : 300,
    "about": "thisi is an updated bio",
    "avatar_url": "thisisuorl.com"
}

###
# DELETE FollWINGS RELATION 
DELETE http://localhost:5173/api/users/14/followings HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlckB1c2VyLmNvbSIsImlkIjoxNCwicm9sZSI6InN1cGVydXNlciIsImlhdCI6MTczMTIzMDUwOCwiZXhwIjoxNzMxMjM0MTA4fQ.0ypWblkIVxxZEuK2Mu7k1YHPck4HLG9kIH8VRmRbU6o

{
    "podcastId" : 23
}

###
# DELETE FollWINGS RELATION 
DELETE http://localhost:5173/api/users/14 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlckB1c2VyLmNvbSIsImlkIjoxNCwicm9sZSI6InN1cGVydXNlciIsImlhdCI6MTczMTIzMDUwOCwiZXhwIjoxNzMxMjM0MTA4fQ.0ypWblkIVxxZEuK2Mu7k1YHPck4HLG9kIH8VRmRbU6o

