# backend-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
type: Opaque
stringData:
  SECRET: 'ep56gNwPyYgQ4ugfmAJYrrA5pY0Q7HjFd6wcm9xWWRIHQwsk75J9WhBXO1ba7kdJKHdU9vIYIzJiSPF787ITug=='
  DATABASE_URL: "postgresql://postgres.awgrvjysdxbyvuxszhih:jKc0WryLX8G2D7Kf@aws-0-eu-central-1.pooler.supabase.com:6543/postgres?pgbouncer=true"
  SUPABASE_URL: "https://awgrvjysdxbyvuxszhih.supabase.co"
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3Z3J2anlzZHhieXZ1eHN6aGloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1NTc3OTgsImV4cCI6MjA1NTEzMzc5OH0.vIxPx0x3rdVlIJPpJX4yYS9L4l_5QaQu2mEtCdzspAQ"
  SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5a2J6eXR6eHF0cmxqZnFzeXVlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTA4MTE0NSwiZXhwIjoyMDU2NjU3MTQ1fQ.DbvaMXV4rQX5LO1ijjfclLcKUByh_lFKGmEm-YE0158"